identifier: k6wcq4o0e53ctf18
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: test-scully-project
homeFolder: C:\Users\ad358\workspace\test-scully-project\test-scully-project
distFolder: dist/test-scully-project
outDir: C:\Users\ad358\workspace\test-scully-project\test-scully-project\dist\static
handle404: ''
allowErrorCollect: false
